services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data 

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    ports:
      - '8080:8080'
    command: -v start-dev --import-realm
    volumes:
      - ./realm:/opt/keycloak/data/import
    depends_on:
      - keycloak-db

volumes:
  pgdata: