server:
    port: 8092
spring:
    application:
        name: payment-service
    datasource:
        username: admin
        password: password
        url: jdbc:mysql://payment-database.cw54gfk857lm.ap-southeast-2.rds.amazonaws.com:3306/payment
        # url: jdbc:sqlserver://listing-database.cw54gfk857lm.ap-southeast-2.rds.amazonaws.com:1433;databaseName=listings;encrypt=false;trustServerCertificate=true;
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    #     properties:
    #         hibernate:
    #             dialect: org.hibernate.dialect.SQLServer2012Dialect
    # hikari:
    #   data-source-properties:
    #     trustServerCertificate: true # Set this to true to trust the server certificate