
spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ezecto/configrepo

server:
    port: 8887