server:
  port: 8069

spring:
  application:
    name: gateway
  cloud:
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: false
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowCredentials: true
            allowed-headers:
              - Content-Type
              - Accept
              - X-Requested-With
              - remember-me
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            maxAge: 3600
      routes:
      - id: tutget-main
        uri: lb://tutget-main
        predicates:
        - Path=/**
        filters:
          - name: CircuitBreaker
            args:
              name: tutget-main-cb
              fallbackUri: forward:/fallback
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              redis-rate-limiter.requestedTokens: 1